# Generated by Django 5.0.6 on 2024-09-12 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_for_school', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999)], verbose_name='Годы работы школы')),
                ('students', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Количество учащихся')),
                ('graduates_per_year', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Выпускников в год')),
                ('count_books', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999)], verbose_name='Количество книг')),
            ],
            options={
                'verbose_name': 'Мы в цифрах',
                'verbose_name_plural': 'Мы в цифрах',
            },
        ),
        migrations.CreateModel(
            name='AdministratorTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choosing', models.CharField(max_length=50, unique=True, verbose_name='Выбор')),
            ],
            options={
                'verbose_name': 'должность среди учащихся',
                'verbose_name_plural': 'Добавить должности среди учащихся',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30, null=True, unique=True, verbose_name='Номер телефона(+996)')),
                ('address', models.CharField(max_length=200, null=True, unique=True, verbose_name='Адрес')),
                ('instagram', models.URLField(null=True, verbose_name='Instagram')),
                ('youtube', models.URLField(null=True, verbose_name='Youtube')),
                ('telegram', models.URLField(null=True, verbose_name='Telegram')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
        migrations.CreateModel(
            name='NamesOfOlympia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choosing', models.CharField(max_length=20, unique=True, verbose_name='Название олимпиады')),
                ('choosing_ky', models.CharField(max_length=20, null=True, unique=True, verbose_name='Название олимпиады')),
                ('choosing_ru', models.CharField(max_length=20, null=True, unique=True, verbose_name='Название олимпиады')),
            ],
            options={
                'verbose_name': 'олимпиаду',
                'verbose_name_plural': 'Добавить олимпиады',
            },
        ),
        migrations.CreateModel(
            name='NameOfGrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], max_length=10, verbose_name='Класс')),
                ('parallel', models.CharField(help_text='Например, А, Б, В и т.д.', max_length=1, verbose_name='Параллель')),
            ],
            options={
                'verbose_name': 'класс',
                'verbose_name_plural': 'Добавить классы',
                'unique_together': {('grade', 'parallel')},
            },
        ),
    ]
