# Generated by Django 5.0.6 on 2024-09-12 14:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secondary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppealToStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('content', models.TextField(verbose_name='Контент')),
                ('content_ky', models.TextField(null=True, verbose_name='Контент')),
                ('content_ru', models.TextField(null=True, verbose_name='Контент')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Заголовок')),
                ('title_ky', models.CharField(db_index=True, max_length=50, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(db_index=True, max_length=50, null=True, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Обращение к ученикам (от выпускников)',
                'verbose_name_plural': 'Обращение к ученикам (от выпускников)',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Изображение')),
                ('content', models.TextField(verbose_name='Контент')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('url_video', models.URLField(blank=True, verbose_name='Ссылка на видео')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галерея',
            },
        ),
        migrations.CreateModel(
            name='Graduates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(db_index=True, max_length=25, verbose_name='Фамилия')),
                ('name', models.CharField(db_index=True, max_length=25, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=25, verbose_name='Отчество')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2024)], verbose_name='Год')),
                ('ort', models.PositiveSmallIntegerField(verbose_name='ОРТ')),
            ],
            options={
                'verbose_name': 'Выпускники',
                'verbose_name_plural': 'Выпускники',
            },
        ),
        migrations.CreateModel(
            name='OurAchievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Изображение')),
                ('content', models.TextField(verbose_name='Контент')),
                ('content_ky', models.TextField(null=True, verbose_name='Контент')),
                ('content_ru', models.TextField(null=True, verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Наши достижения',
                'verbose_name_plural': 'Наши достижения',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(db_index=True, max_length=25, verbose_name='Фамилия')),
                ('name', models.CharField(db_index=True, max_length=25, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=25, verbose_name='Отчество')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Изображение')),
                ('experience', models.CharField(choices=[('Год', 'Более 1 года'), ('От пяти лет', 'Более 5 лет'), ('От десяти лет', 'Более 15 лет')], max_length=200, verbose_name='Опыт')),
                ('subject', models.CharField(max_length=200, verbose_name='Предмет')),
                ('subject_ky', models.CharField(max_length=200, null=True, verbose_name='Предмет')),
                ('subject_ru', models.CharField(max_length=200, null=True, verbose_name='Предмет')),
                ('education', models.TextField(blank=True, verbose_name='Образование')),
                ('education_ky', models.TextField(blank=True, null=True, verbose_name='Образование')),
                ('education_ru', models.TextField(blank=True, null=True, verbose_name='Образование')),
                ('successes', models.TextField(blank=True, verbose_name='Успехи')),
                ('successes_ky', models.TextField(blank=True, null=True, verbose_name='Успехи')),
                ('successes_ru', models.TextField(blank=True, null=True, verbose_name='Успехи')),
            ],
            options={
                'verbose_name': 'Учителя',
                'verbose_name_plural': 'Учителя',
            },
        ),
        migrations.CreateModel(
            name='ThanksNoteFromGraduates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Изображение')),
                ('content', models.TextField(verbose_name='Контент')),
                ('content_ky', models.TextField(null=True, verbose_name='Контент')),
                ('content_ru', models.TextField(null=True, verbose_name='Контент')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Заголовок')),
                ('title_ky', models.CharField(db_index=True, max_length=50, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(db_index=True, max_length=50, null=True, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Благодарственное письмо (от выпускников)',
                'verbose_name_plural': 'Благодарственное письмо (от выпускников)',
            },
        ),
        migrations.CreateModel(
            name='ThanksNoteFromStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Изображение')),
                ('content', models.TextField(verbose_name='Контент')),
                ('content_ky', models.TextField(null=True, verbose_name='Контент')),
                ('content_ru', models.TextField(null=True, verbose_name='Контент')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Заголовок')),
                ('title_ky', models.CharField(db_index=True, max_length=50, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(db_index=True, max_length=50, null=True, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Благодарственное письмо (от учеников)',
                'verbose_name_plural': 'Благодарственное письмо (от учеников)',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Изображение')),
                ('content', models.TextField(verbose_name='Контент')),
                ('content_ky', models.TextField(null=True, verbose_name='Контент')),
                ('content_ru', models.TextField(null=True, verbose_name='Контент')),
                ('description', models.CharField(max_length=300, verbose_name='Описание')),
                ('description_ky', models.CharField(max_length=300, null=True, verbose_name='Описание')),
                ('description_ru', models.CharField(max_length=300, null=True, verbose_name='Описание')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(db_index=True, max_length=25, verbose_name='Фамилия')),
                ('name', models.CharField(db_index=True, max_length=25, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=25, verbose_name='Отчество')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Изображение')),
                ('administrator_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secondary.administratortypes', verbose_name='Позиция')),
                ('olympian_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secondary.namesofolympia', verbose_name='Олимпиец')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondary.nameofgrades', verbose_name='Класс')),
                ('classroom_teacher', models.ManyToManyField(to='main.teachers', verbose_name='Классный руководитель')),
            ],
            options={
                'verbose_name': 'Ученики',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.CreateModel(
            name='SchoolParliament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_administrator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secondary.administratortypes', verbose_name='Должность')),
                ('student', models.ManyToManyField(blank=True, to='main.students', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Парламент нашей гимназии',
                'verbose_name_plural': 'Парламент нашей гимназии',
            },
        ),
        migrations.CreateModel(
            name='Olympians',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_olympia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='secondary.namesofolympia', verbose_name='Предмет')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.students', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Олимпийцы',
                'verbose_name_plural': 'Олимпийцы',
            },
        ),
        migrations.CreateModel(
            name='GimnasiumClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondary.nameofgrades', verbose_name='Класс')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.students', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Классы Гимназии №3',
                'verbose_name_plural': 'Классы Гимназии №3',
            },
        ),
        migrations.CreateModel(
            name='SuccessfulGraduates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Изображение')),
                ('content', models.TextField(verbose_name='Контент')),
                ('content_ky', models.TextField(null=True, verbose_name='Контент')),
                ('content_ru', models.TextField(null=True, verbose_name='Контент')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('graduate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.graduates', verbose_name='Выберите его(её) из списка')),
            ],
            options={
                'verbose_name': 'Успешные выпускники',
                'verbose_name_plural': 'Успешные выпускники',
            },
        ),
        migrations.AddField(
            model_name='graduates',
            name='kl_rukovoditel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduates_teachers', to='main.teachers', verbose_name='Классный руководитель'),
        ),
        migrations.AddIndex(
            model_name='students',
            index=models.Index(fields=['school_class'], name='main_studen_school__135546_idx'),
        ),
        migrations.AddIndex(
            model_name='students',
            index=models.Index(fields=['olympian_status'], name='main_studen_olympia_eed431_idx'),
        ),
        migrations.AddIndex(
            model_name='students',
            index=models.Index(fields=['administrator_status'], name='main_studen_adminis_80a678_idx'),
        ),
    ]
