JAZZMIN_SETTINGS = {
    "site_title": "Гимназия №3",
    "site_header": "Гимназия №3",
    "site_logo_classes": "img-circle",
    "site_brand": "Админ-панель",
    "welcome_sign": "Добро пожаловать в админ-панель сайта Гимназии №3",
    "copyright": "Гимназия №3",
    "search_model": ["auth.User"],
    "topmenu_links": [
        {"name": "Главная", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"app": "Гимназия №3"},
        {"model": "auth.User"},
    ],
    "default_icon_parents": "fas fa-circle",
    "default_icon_children": "fas fa-dot-circle",
    "show_sidebar": True,
    "navigation_expanded": True,
    "changeform_format": "horizontal_tabs",
    "language_chooser": True,
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
    "hide_apps": ["django_celery_beat"],
    "icons": {
        "account.EmailAddress": "fas fa-solid fa-envelope",
        "socialaccount.SocialAccount": "fas fa-solid fa-share-alt",
        "socialaccount.SocialApp": "fas fa-solid fa-mobile-alt",
        "socialaccount.SocialToken": "fas fa-solid fa-key",
        "auth.Group": "fas fa-users",
        "auth.User": "fas fa-user",
        "main.Students": "fas fa-solid fa-graduation-cap",
        "main.SchoolParliament": "fas fa-solid fa-university",
        "main.GimnasiumClass": "fas fa-solid fa-chalkboard",
        "main.ThanksNoteFromStudents": "fas fa-solid fa-envelope",
        "main.Olympians": "fas fa-solid fa-trophy",
        "main.SuccessfulGraduates": "fas fa-solid fa-star",
        "main.AppealToStudents": "fas fa-solid fa-bullhorn",
        "main.Graduates": "fas fa-solid fa-user-graduate",
        "main.ThanksNoteFromGraduates": "fas fa-solid fa-envelope-open-text",
        "main.News": "fas fa-solid fa-newspaper",
        "main.Gallery": "fas fa-solid fa-images",
        "main.OurAchievements": "fas fa-solid fa-award",
        "main.Teachers": "fas fa-solid fa-chalkboard-teacher",
        "main.Contacts": "fas fa-solid fa-address-book",
        "secondary.NameOfGrades": "fas fa-solid fa-list-ol",
        "secondary.AdministratorTypes": "fas fa-solid fa-user-tie",
        "secondary.NamesOfOlympia": "fas fa-solid fa-medal",
        "secondary.AboutUs": "fas fa-chart-bar",
        "secondary.Contacts": "fas fa-address-book",
        "users.UserProfile": "fas fa-id-card",
        "users.Comment": "fas fa-comment",
        "users.CommentReply": "fas fa-reply",
        "users.Like": "fas fa-thumbs-up",
        "users.Donation": "fas fa-hand-holding-usd",
        "users.ConfirmedDonation": "fas fa-check-circle",


    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": True,
    "footer_small_text": True,
    "body_small_text": True,
    "brand_small_text": True,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-warning",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-outline-info",
        "warning": "btn-outline-warning",
        "danger": "btn-outline-danger",
        "success": "btn-outline-success",
    },
    "actions_sticky_top": True,
}